package ar.com.g5one.conversormoneda.view;

import ar.com.g5one.conversormoneda.view.resources.ValidadorDeCampos;
import java.awt.Color;

/**
 *
 * @author nadia
 */
public class JPanel_Moneda extends javax.swing.JPanel {

    private JPanelAplication panelMenu;
    ValidadorDeCampos validadorDeCampos;

    public JPanel_Moneda(JPanelAplication panelMenu) {

        this.validadorDeCampos = new ValidadorDeCampos();
        this.panelMenu = panelMenu;
        initComponents();
        validadarCampos();

        setupBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTf_cotizaciondia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTf_monto = new javax.swing.JTextField();
        jbt_convertir = new javax.swing.JButton();
        jButton_salir = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 153, 255));

        jTf_cotizaciondia.setText("jTextField1");

        jLabel1.setText("Cotización día:");

        jLabel2.setText("Monto a convertir:");

        jTf_monto.setText("jTextField1");

        jbt_convertir.setText("CONVERTIR");
        jbt_convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_convertirActionPerformed(evt);
            }
        });

        jButton_salir.setText("SALIR");
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTf_cotizaciondia, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbt_convertir)
                            .addComponent(jTf_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_salir)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTf_cotizaciondia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTf_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jbt_convertir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton_salir)
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_convertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_convertirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_convertirActionPerformed

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
        this.panelMenu.bloquearBotones(true);
        this.panelMenu.limpiarPanelContenido();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTf_cotizaciondia;
    private javax.swing.JTextField jTf_monto;
    private javax.swing.JButton jbt_convertir;
    // End of variables declaration//GEN-END:variables

    private void validadarCampos() {
        this.validadorDeCampos.validarSoloNumero(jTf_cotizaciondia);
        this.validadorDeCampos.validarSoloNumero(jTf_monto);
        //this.validadorDeCampos.LimitarCaracteres(jtx_buyerDni, 8);
    }

    private void setupBotones() {
        this.validadorDeCampos.habilitarBoton(true, jButton_salir, new Color(176, 128, 118), Color.WHITE, Color.GRAY, Color.BLACK);
    }

}
