package ar.com.g5one.conversormoneda.view;

import ar.com.g5one.conversormoneda.controller.MonedaController;
import ar.com.g5one.conversormoneda.view.resources.ValidadorDeCampos;
import java.awt.Color;

/**
 *
 * @author nadia
 */
public class JPanel_Moneda extends javax.swing.JPanel {

    private MonedaController controlador;
    private JPanelAplication panelMenu;
    ValidadorDeCampos validadorDeCampos;

    public JPanel_Moneda(JPanelAplication panelMenu, MonedaController monedaController) {

        this.validadorDeCampos = new ValidadorDeCampos();
        this.panelMenu = panelMenu;
        this.controlador = monedaController;
        initComponents();
       // validadarCampos();

        setupBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTf_monto = new javax.swing.JTextField();
        jbt_convertir = new javax.swing.JButton();
        jButton_salir = new javax.swing.JButton();
        jComboBox_opcion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Monto a convertir:");

        jbt_convertir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbt_convertir.setText("CONVERTIR");
        jbt_convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_convertirActionPerformed(evt);
            }
        });

        jButton_salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_salir.setText("SALIR");
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });

        jComboBox_opcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pesos/Dólar", "Pesos/Euros", "Pesos/Libras Esterlinas", "Pesos/Jen Japonés", "Pesos/Won Sul-Coreano", "Dólar/Pesos", "Euros/Pesos", "Libras Esterlinas/Pesos", "Jen Japónes/Pesos", "Won Sul-Coreano/Pesos", " " }));
        jComboBox_opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_opcionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Tipo de Cambio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbt_convertir)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTf_monto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox_opcion, javax.swing.GroupLayout.Alignment.TRAILING, 0, 167, Short.MAX_VALUE)))
                    .addComponent(jButton_salir))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTf_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_opcion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jbt_convertir)
                .addGap(45, 45, 45)
                .addComponent(jButton_salir)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_convertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_convertirActionPerformed
        
            Double monto = Double.parseDouble(jTf_monto.getText());
            int opcion = jComboBox_opcion.getSelectedIndex();
            this.controlador.Convertir(monto, opcion);
        
            
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_convertirActionPerformed

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
        this.panelMenu.bloquearBotones(true);
        this.panelMenu.limpiarPanelContenido();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jComboBox_opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_opcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_opcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_salir;
    private javax.swing.JComboBox<String> jComboBox_opcion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTf_monto;
    private javax.swing.JButton jbt_convertir;
    // End of variables declaration//GEN-END:variables

    private void validadarCampos() {
       // this.validadorDeCampos.validarSoloNumero(jTf_cotizaciondia);
       // this.validadorDeCampos.validarSoloNumero(jTf_monto);
       
    }

    private void setupBotones() {
        this.validadorDeCampos.habilitarBoton(true, jButton_salir, new Color(176, 128, 118), Color.WHITE, Color.GRAY, Color.BLACK);
    }



}
